### ISSUE TITLE
Apple Silicon Support

### ISSUE THREAD

**Issue by jayemmsea** [matthias-vogt/wttr-moon-uebersicht#3]
Hey! This needs to be packaged with an arm version of the terminal-to-html executable to function on Apple silicon.

**Comment by juni-vogt** [comment]
Hi, I think it's fixed now. Could you please verify?

**Comment by jayemmsea** [comment]
Unfortunately, it does not seem to be finding the right binary for some reason. I'm actually getting the same error that I got before I got my personal version working by replacing the old terminal-to-html.  I took a look but I couldn't find anything wrong, even replacing the binaries with fresh versions just to see. I suppose for an easier fix you could fork a separate apple silicon-only version but I cant see any reason why the shell script wouldn't work.

**Comment by jayemmsea** [comment]
> Unfortunately, it does not seem to be finding the right binary for some reason. I'm actually getting the same error that I got before I got my personal version working by replacing the old terminal-to-html. I took a look but I couldn't find anything wrong, even replacing the binaries with fresh versions just to see. I suppose for an easier fix you could fork a separate apple silicon-only version but I cant see any reason why the shell script wouldn't work.

Aha nevermind! I can confirm it does work. I was being silly. I had changed the name of the folder name because I still had the old widget installed, but of course that would confuse. Thanks!

**Comment by juni-vogt** [comment]
Beautiful, thank you so much for your help!

**Comment by jayemmsea** [comment]
Any time! I imagine this same fix can be implemented for the main wttr.in widget as well!

**Comment by juni-vogt** [comment]
Yes, I will update it tomorrow.
